---
title: "R Notebook"
output: html_notebook
---

```{r}
library(devtools)

devtools::load_all()

required_packages <- c(
  'scales',
  'httr',
  'jsonlite',
  'lubridate',
  'tidyselect',
  'dplyr',
  'prophet'
)

for (pkg in required_packages) {
  require(pkg)
}

```


```{r}
r <- GET("https://community-api.coinmetrics.io/v4/timeseries/asset-metrics?assets=usdc&metrics=CapMrktCurUSD&page_size=10000")

t <- httr::content(r, as = 'text', encoding = 'UTF-8') %>% jsonlite::fromJSON() %>% .$data

df <- t %>%
  rename(
    date = `time`,
    circulating_supply = `CapMrktCurUSD`
  ) %>% select(-asset) %>%
  mutate(
    date = lubridate::as_date(date),
    blockchain = 'Ethereum')
  
  
```


```{r}
ethereum_historical(metric = 'CapMrktCurUSD') %>%
  select(date, value) %>%
  rename(ds = date,
         y = value)

m <- prophet(rf)

future <- make_future_dataframe(m, periods = 12, freq = "month")
forecast <- predict(m, future)
plot(m, forecast, plot_cap = FALSE) +
  scale_x_datetime(date_breaks = "3 month", date_labels = '%b %y', expand = c(0,0), 
                   limits = c(ymd_hms(20200101000000), ymd_hms(20220315000000))) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1))

```
